---

- name: install basics
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  become: yes
  with_items:
  - zsh
  - tree
  - htop
  - zip
  - wget
  - unrar
  - unzip
  - git
  - tig
  - sed
  - apg
  - nmap
  - build-essential
  - curl
  - jq
  - psmisc
  when: ansible_system == 'Linux'

- name: install basics on MacOS X
  homebrew: name={{ item }} state=present
  with_items:
  - zsh
  - tree
  - htop
  - zip
  - curl
  - fzf
  - macvim
  - ctags
  - git
  - tig
  - glide
  - gnupg
  - jq
  - openssh
  - pstree
  - unrar
  - p7zip
  when: ansible_system == 'darwin'

- name: create proj directory
  file: path=~/proj state=directory

