---

- name: install basics
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  become: yes
  with_items:
  - zsh
  - tree
  - htop
  - zip
  - wget
  - unrar
  - unzip
  - git
  - tig
  - sed
  - apg
  - nmap
  - build-essential
  - curl
  when: ansible_system == 'Linux'

- name: create proj directory
  file: path=~/proj state=directory

