---

- name: install basics
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  become: yes
  with_items:
  - zsh
  - tree
  - htop
  - zip
  - wget
  - unrar
  - unzip
  - git
  - tig
  - sed
  - apg
  - nmap
  - build-essential
  - curl
  - jq
  - psmisc
  - silversearcher-ag
  - pstree
  - fzf
  - ripgrep
  when: ansible_system == 'Linux'

- name: install basics on MacOS X
  homebrew: name={{ item }} state=present
  with_items:
  - zsh
  - tree
  - htop
  - zip
  - curl
  - fzf
  - git
  - tig
  - glide
  - gnupg
  - jq
  - openssh
  - pstree
  - unrar
  - p7zip
  - ripgrep
  when: ansible_system == 'darwin'

- name: create src directory
  file: path=~/src/github.com/ilikeorangutans state=directory

- name: clone/update dotfiles
  git: repo=git@github.com:ilikeorangutans/dotfiles.git dest=~/src/github.com/ilikeorangutans/dotfiles

