---

- name: install vim and dependencies
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
  - vim
  - vim-common
  - vim-gtk
  tags:
  - vim

- name: link gvim config
  file: src=~/proj/vimrc/gvimrc dest=~/.gvimrc state=link




