---

- name: install vim and dependencies (Linux)
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  become: yes
  with_items:
  - vim
  - vim-common
  - vim-gtk
  - exuberant-ctags
  - cmake
