---

- include: "{{ansible_system}}.yml"

- name: link vimrc config
  file: src=~/src/github.com/ilikeorangutans/dotfiles/vimrc dest=~/.vimrc state=link

- name: link gvim config
  file: src=~/src/github.com/ilikeorangutans/dotfiles/gvimrc dest=~/.gvimrc state=link

- name: ensure .vim and subdirs exist
  file:
    path: ~/.vim/{{item}}
    state: directory
  with_items:
    - swap
    - backup

- name: check for bundle directory
  stat: path=~/.vim/bundle
  register: p

- name: install vundle
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: ~/.vim/bundle/Vundle.vim
  when: p.stat.isdir is not defined

- name: install vundle plugins
  shell: vim +PluginInstall +qall
  when: p.stat.isdir is not defined

- name: update vundle  plugins
  shell: vim +PluginUpdate +qall
  when: p.stat.exists is defined and p.stat.isdir and ansible_date_time.epoch|int - p.stat.mtime|int > 1800

- name: YouCompleteMe last updated at
  stat: path=~/.vim/bundle/YouCompleteMe
  register: ycm

  #- name: recompile YouCompleteMe
  #shell: ./install.py --clang-completer --gocode-completer chdir=~/.vim/bundle/YouCompleteMe
  #when: ansible_date_time.epoch|int - ycm.stat.mtime|int > 3600

- name: recompile ctrlp-cmatcher
  shell: ./install.sh chdir=~/.vim/bundle/ctrlp-cmatcher/
  # TODO ctrlp-cmatcher doesn't work on ubuntu any more. Gotta figure out what to do with it.
  # TODO might switch to fzf
