---

- include: "{{ansible_system}}.yml"

- name: link vimrc config
  file: src=~/src/github.com/ilikeorangutans/dotfiles/vimrc dest=~/.vimrc state=link

- name: link gvim config
  file: src=~/src/github.com/ilikeorangutans/dotfiles/gvimrc dest=~/.gvimrc state=link

- name: check for bundle directory
  stat: path=~/.vim/bundle
  register: p

- name: install vundle plugins
  shell: vim +PluginInstall +qall
  when: p.stat.isdir is not defined

- name: update vundle  plugins
  shell: vim +PluginUpdate +qall
  when: p.stat.exists is defined and p.stat.isdir

- name: recompile YouCompleteMe
  shell: ./install.py --clang-completer --gocode-completer chdir=~/.vim/bundle/YouCompleteMe

- name: recompile ctrlp-cmatcher
  shell: ./install.sh chdir=~/.vim/bundle/ctrlp-cmatcher/
  # TODO ctrlp-cmatcher doesn't work on ubuntu any more. Gotta figure out what to do with it.
  # TODO might switch to fzf
